export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_FILTERED_COUNTRIES = 'GET_FILTERED_COUNTRIES';
export const POST_ACTIVITIES = 'POST_ACTIVITIES';
export const SORT_COUNTRIES = 'SORT_COUNTRIES';
export const FILTER_COUNTRIES_BY_ACTIVITY = 'FILTER_COUNTRIES_BY_ACTIVITY';
export const FILTER_COUNTRIES_BY_CONTINENT = 'FILTER_COUNTRIES_BY_CONTINENT';
export const FILTER_COUNTRIES_BY_AREA = 'FILTER_COUNTRIES_BY_AREA';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const ERROR = 'ERROR';

